---
title: "move_times"
output: html_document
date: "2024-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
library(interactions)
library(lmerTest)
library(viridis)
library(hrbrthemes)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/ETH_GitHub_Repos/rpg_trajectory_evaluation/R_analysis/kitti_data/")
task_df <- read_csv("all_percentages.csv")

detector_order <- c("sift", "harris", "shi_tomasi")

# Reorder the factor levels
task_df$detector <- factor(task_df$detector, levels = detector_order)

# some new columns
task_df$percent_tracked <- task_df$tracked * 100
task_df$percent_inliers <- task_df$inliers * 100
task_df$detect_time_ms <- task_df$detect_time * 1000

task_df$new_detector <- task_df$detector
levels(task_df$new_detector) <- c("SIFT", "Harris", "S-T")


######################### get mean and sd (or se) ######################### 
task_df %>%
  group_by(detector) %>%
  get_summary_stats(detect_time_ms, type = "mean_sd")

######################### get mean and sd (or se) ######################### 
task_df %>%
  group_by(detector) %>%
  get_summary_stats(percent_tracked, type = "mean_sd")


```

## Plots

```{r do plotting}

bxp1 <- ggboxplot(
  task_df, x = "new_detector", y = "percent_tracked", palette = "uchicago", outlier.shape = NA,
  color = "new_detector", xlab = "Detector", ylab = "Tracked Keypoints (%)"
  ) + ylim(85, 100) + 
  theme(legend.position="none", 
        axis.text=element_text(size=20),
        axis.title=element_text(size=22))
bxp1

bxp2 <- ggboxplot(
  task_df, x = "new_detector", y = "detect_time_ms", palette = "uchicago", outlier.shape = NA,
  color = "new_detector", xlab = "Detector", ylab = "Runtime Per Frame (ms)"
  ) + ylim(0, 100) + 
  theme(legend.position="none", 
        axis.text=element_text(size=20),
        axis.title=element_text(size=22))
bxp2


ggsave(file="plots/percent_tracked.pdf", plot=bxp1, width=3.5, height=5)
ggsave(file="plots/detect_time.pdf", plot=bxp2, width=3.5, height=5)


```


## Check assumptions

```{r check assumptions}

# ######################### check for outliers ######################### 
# task_df %>%
#   group_by(dist_factor) %>%
#   identify_outliers(trans_err)
# 
# ######################### check normality ######################### 
# task_df %>%
#   group_by(auto_level, ring_id) %>%
#   shapiro_test(average_mt)
# 
# ######################### plot normality ######################### 
# ggqqplot(task_df, "average_mt", ggtheme = theme_bw()) +
#   facet_grid(ring_id ~ auto_level, labeller = "label_both")


```


## Fit ANOVA

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(
  data = task_df, dv = tracked, wid = frame_id,
  within = detector
  )
get_anova_table(res.aov)

pwc1 <- task_df %>%
  pairwise_t_test(
    tracked ~ detector, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc1


######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(
  data = task_df, dv = inliers, wid = frame_id,
  within = detector
  )
get_anova_table(res.aov)

pwc2 <- task_df %>%
  pairwise_t_test(
    inliers ~ detector, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc2

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(
  data = task_df, dv = detect_time, wid = frame_id,
  within = detector
  )
get_anova_table(res.aov)

pwc2 <- task_df %>%
  pairwise_t_test(
    detect_time ~ detector, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc2



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
